### PR TITLE
Jw 499 signwin

### PR DESCRIPTION
**Pull request by mmasztalerczuk**

### CODE REVIEW

**Comment by mmasztalerczuk** [comment]
Retest this please

**Comment by mmasztalerczuk** [comment]
Retest this please

**Comment by mmasztalerczuk** [comment]
Retest this please

**Comment by mmasztalerczuk** [comment]
Retest this please

**Comment by mmasztalerczuk** [comment]
Retest this please

**Comment by mmasztalerczuk** [comment]
Retest this please

**Comment by sodar** [comment]
Retest this please

**Comment by sodar** [comment]
Retest this please

**Pull request merged**
