### PR TITLE
JW-383: moved if_* functions to vif.c

### PR DESCRIPTION
**Pull request by sodar**

### CODE REVIEW

**Comment by m-kostrzewa** [comment]
One eternity later... :hourglass_flowing_sand: :dancer:

**Comment by sodar** [comment]
@m-kostrzewa https://www.youtube.com/watch?v=bDQpF92l1vg

**Comment by sodar** [comment]
Retest this please

**Comment by sodar** [comment]
Retest this please

**Comment by sodar** [comment]
Retest this please

**Comment by sodar** [comment]
Retest this please

**Pull request closed without merging**
