### PR TITLE
JW-352 Fixed two overlooked bugs.

### PR DESCRIPTION
**Pull request by Attil**
One was a misplaced else and another one was an inverted if.

### CODE REVIEW

**Comment by mmasztalerczuk** [comment]
There is something what looks like dead code in line vrouter_mod.c:338. I think that it should be also fixed.

**Comment by sodar** [comment]
I agree with @mmasztalerczuk. This part from vrouter_mod.c:338.

```c
    status = SxExtInitializeVRouter(ctx);

    if (!NT_SUCCESS(status))
        goto cleanup;

    vrouter = TRUE;

    return NDIS_STATUS_SUCCESS;

cleanup:
    if (vrouter)
        SxExtUninitializeVRouter(ctx);
```

If `SxExtInitializeVRouter(ctx)`, then `vrouter` flag is not set, so `SxExtUninitializeVRouter(ctx)` will not be called on cleanup.

Also, `SxExtUninitializeVRouter` is called inside `SxExtInitializeVRouter` in case of failure, so this call is not needed here.

**Comment by Attil** [comment]
This is intentionally dead code, it will be optimized away by compiler. I added it to preserve some symmetry and secure ourselves in case on someone adding code to this function.

**Comment by Attil** [comment]
Retest this please

**Pull request merged**
